POST http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
  "title": "Test comments ",
  "isDone": true,
  "author":{
    "name": "p ew",
    "email" : "qwe@fasfdsgdf.com",
    "age": 50
  }
}